# Copyright © 2021 General Motors Co open.source@gm.com
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; version 2.0
# of the License or any later version. This library is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License 2 for more details.
#
# The source for this package can be downloaded at:
# https://www.oss.gm.com/GMNA/7E7/IVAIVD
#
# Makefile for GM security module
#

obj-$(CONFIG_GM_SIGNATURE) += gm_signature.o
